<?php
/*
 * Plugin Name: Live 2D
 * Plugin URI: https://5ri.org
 * Description: 看板娘插件
 * Version: 1.0
 * Author: jiangweifang
 * Author URI: https://5ri.org
 * License: MIT
 */
//定义css根目录
define( 'LIVE2D_ASSETS', plugin_dir_url( __FILE__ ) . 'assets/' );
define('LIVE2D_BASEFOLDER', plugin_basename(dirname(__FILE__)));

//添加样式

function live2D_style(){
	wp_enqueue_style( 'waifu_css' ,LIVE2D_ASSETS . "waifu.css");//css
	wp_enqueue_script( 'jquery');//js
	wp_enqueue_script( 'jquery-ui' ,LIVE2D_ASSETS.'jquery-ui.min.js');//js
   wp_enqueue_script( 'waifu-tips_js' ,LIVE2D_ASSETS.'waifu-tips.js');//js
	wp_enqueue_script( 'live2d_js' ,LIVE2D_ASSETS.'live2d.js');//js
	
}
add_action( 'init', 'live2D_style' );
add_action( 'wp_footer', 'live2D_DefMod' );
function live2D_DefMod(){
	echo '<div class="waifu">
        <div class="waifu-tips"></div>
        <canvas id="live2d" class="live2d"></canvas>
        <div class="waifu-tool">
            <span class="fui-home"></span>
            <span class="fui-chat"></span>
            <span class="fui-eye"></span>
            <span class="fui-user"></span>
            <span class="fui-photo"></span>
            <span class="fui-info-circle"></span>
            <span class="fui-cross"></span>
        </div>
    </div>';
	echo '<script type="text/javascript">
        /* 可直接修改部分参数 */
        live2d_settings["modelId"] = 1;                  // 默认模型 ID
        live2d_settings["modelTexturesId"] = 87;         // 默认材质 ID
        live2d_settings["modelStorage"] = false;         // 不储存模型 ID
        live2d_settings["canCloseLive2d"] = false;       // 隐藏 关闭看板娘 按钮
        live2d_settings["canTurnToHomePage"] = false;    // 隐藏 返回首页 按钮
        live2d_settings["waifuSize"] = "600x535";        // 看板娘大小
        live2d_settings["waifuTipsSize"] = "570x150";    // 提示框大小
        live2d_settings["waifuFontSize"] = "30px";       // 提示框字体
        live2d_settings["waifuToolFont"] = "36px";       // 工具栏字体
        live2d_settings["waifuToolLine"] = "50px";       // 工具栏行高
        live2d_settings["waifuToolTop"] = "-60px";       // 工具栏顶部边距
        live2d_settings["waifuDraggable"] = "axis-x";    // 拖拽样式
        /* 在 initModel 前添加 */
        initModel("'. assets .'waifu-tips.json?v=1.4.2")
    </script>';
}

// 停用插件
register_deactivation_hook(__FILE__, 'live_2d_stop');
function live_2d_stop ()
{
	
}

/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class LiveD {
	private $live_2d__options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'live_2d__add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'live_2d__page_init' ) );
	}

	public function live_2d__add_plugin_page() {
		add_options_page(
			'Live 2D 设置', // page_title
			'Live 2D 设置', // menu_title
			'manage_options', // capability
			'live-2d-', // menu_slug
			array( $this, 'live_2d__create_admin_page' ) // function
		);
	}

	public function live_2d__create_admin_page() {
		$this->live_2d__options = get_option( 'live_2d__option_name' ); ?>

		<div class="wrap">
			<h2>Live 2D 设置</h2>
			<p>看板娘设置</p>
			<?php settings_errors(); ?>
<h2 class="nav-tab-wrapper">
    <a class="nav-tab">后端接口</a>
    <a class="nav-tab">默认模型</a>
	 <a class="nav-tab">工具栏设置</a>
    <a class="nav-tab">模型切换模式</a>
	 <a class="nav-tab">提示消息选项</a>
    <a class="nav-tab">看板娘样式设置</a>
	 <a class="nav-tab">其他杂项设置</a>
  </h2>
			<form method="post" action="options.php">
				<?php
					settings_fields( 'live_2d__option_group' );
					do_settings_sections( 'live-2d--admin' );
					submit_button();
				?>
			</form>
		</div>
	<?php }

	public function live_2d__page_init() {
		register_setting(
			'live_2d__option_group', // option_group
			'live_2d__option_name', // option_name
			array( $this, 'live_2d__sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'live_2d__setting_section', // id
			'后端接口', // title
			array( $this, 'live_2d__section_info' ), // callback
			'live-2d--admin' // page
		);

		add_settings_field(
			'modelapi_0', // id
			'自建 API 修改这里', // title
			array( $this, 'modelapi_0_callback' ), // callback
			'live-2d--admin', // page
			'live_2d__setting_section' // section
		);

		add_settings_field(
			'tipsmessage_1', // id
			'waifu-tips.json 路径', // title
			array( $this, 'tipsmessage_1_callback' ), // callback
			'live-2d--admin', // page
			'live_2d__setting_section' // section
		);

		add_settings_field(
			'hitokotoapi_2', // id
			'一言 API', // title
			array( $this, 'hitokotoapi_2_callback' ), // callback
			'live-2d--admin', // page
			'live_2d__setting_section' // section
		);
	}

	public function live_2d__sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['modelapi_0'] ) ) {
			$sanitary_values['modelapi_0'] = sanitize_text_field( $input['modelapi_0'] );
		}

		if ( isset( $input['tipsmessage_1'] ) ) {
			$sanitary_values['tipsmessage_1'] = sanitize_text_field( $input['tipsmessage_1'] );
		}

		if ( isset( $input['hitokotoapi_2'] ) ) {
			$sanitary_values['hitokotoapi_2'] = $input['hitokotoapi_2'];
		}

		return $sanitary_values;
	}

	public function live_2d__section_info() {
		
	}

	public function modelapi_0_callback() {
		printf(
			'<input class="regular-text" type="text" name="live_2d__option_name[modelapi_0]" id="modelapi_0" value="%s">',
			isset( $this->live_2d__options['modelapi_0'] ) ? esc_attr( $this->live_2d__options['modelapi_0']) : ''
		);
	}

	public function tipsmessage_1_callback() {
		printf(
			'<input class="regular-text" type="text" name="live_2d__option_name[tipsmessage_1]" id="tipsmessage_1" value="%s">',
			isset( $this->live_2d__options['tipsmessage_1'] ) ? esc_attr( $this->live_2d__options['tipsmessage_1']) : ''
		);
	}

	public function hitokotoapi_2_callback() {
		?> <select name="live_2d__option_name[hitokotoapi_2]" id="hitokotoapi_2">
			<?php $selected = (isset( $this->live_2d__options['hitokotoapi_2'] ) && $this->live_2d__options['hitokotoapi_2'] === 'lwl12.com') ? 'selected' : '' ; ?>
			<option <?php echo $selected; ?>>lwl12.com</option>
			<?php $selected = (isset( $this->live_2d__options['hitokotoapi_2'] ) && $this->live_2d__options['hitokotoapi_2'] === 'hitokoto.cn') ? 'selected' : '' ; ?>
			<option <?php echo $selected; ?>>hitokoto.cn</option>
			<?php $selected = (isset( $this->live_2d__options['hitokotoapi_2'] ) && $this->live_2d__options['hitokotoapi_2'] === 'jinrishici.com') ? 'selected' : '' ; ?>
			<option <?php echo $selected; ?>>jinrishici.com(古诗词)</option>
		</select> <?php
	}

}
if ( is_admin() )
	$live_2d_ = new LiveD();

/* 
 * Retrieve this value with:
 * $live_2d__options = get_option( 'live_2d__option_name' ); // Array of All Options
 * $modelapi_0 = $live_2d__options['modelapi_0']; // modelAPI
 * $tipsmessage_1 = $live_2d__options['tipsmessage_1']; // tipsMessage
 * $hitokotoapi_2 = $live_2d__options['hitokotoapi_2']; // hitokotoAPI
 */
$live_2d__options = get_option( 'live_2d__option_name' ); // Array of All Options
$modelapi = $live_2d__options['modelapi_0']; // modelAPI
$tipsmessage = $live_2d__options['tipsmessage_1']; // tipsMessage
$hitokotoapi = $live_2d__options['hitokotoapi_2']; // hitokotoAPI

?>