<?php
/*
 * Plugin Name: Live 2D
 * Plugin URI: https://5ri.org
 * Description: 看板娘插件
 * Version: 1.0
 * Author: jiangweifang
 * Author URI: https://5ri.org
 * License: MIT
 */
//定义目录
define( 'LIVE2D_ASSETS', plugin_dir_url( __FILE__ ) . 'assets/' );//资源目录
define('LIVE2D_BASEFOLDER', plugin_basename(dirname(__FILE__)));//基础目录
define('LIVE2D_SETTINGPAGE', plugin_basename(__FILE__));//设置页面

//添加样式（初始化）

function live2D_style(){
	wp_enqueue_style( 'waifu_css' ,LIVE2D_ASSETS . "waifu.css");//css
	wp_enqueue_script( 'jquery');//js
	wp_enqueue_script( 'jquery-ui' ,LIVE2D_ASSETS.'jquery-ui.min.js');//js
   wp_enqueue_script( 'waifu-tips_js' ,LIVE2D_ASSETS.'waifu-tips.js');//js
	wp_enqueue_script( 'live2d_js' ,LIVE2D_ASSETS.'live2d.js');//js
	
}
add_action( 'init', 'live2D_style' );


// 停用插件
register_deactivation_hook(__FILE__, 'live_2d_stop');
function live_2d_stop ()
{
	
}
/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class LiveD {
	private $live_2d__options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'live_2d__add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'live_2d__page_init' ) );
	}

	public function live_2d__add_plugin_page() {
		add_options_page(
			'Live 2D 设置', // page_title
			'Live 2D 设置', // menu_title
			'manage_options', // capability
			'live-2d-', // menu_slug
			array( $this, 'live_2d__create_admin_page' ) // function
		);
	}

	public function live_2d__create_admin_page() {
		$this->live_2d__options = get_option( 'live_2d__option_name' ); ?>

		<div class="wrap">
			<h2>Live 2D 设置</h2>
			<form method="post" action="options.php">
				<?php
					settings_fields( 'live_2d__option_group' );
					do_settings_sections( 'live-2d--admin' );
					submit_button();
				?>
			</form>
		</div>
	<?php }

	public function live_2d__page_init() {
		register_setting(
			'live_2d__option_group', // option_group
			'live_2d__option_name', // option_name
			array( $this, 'live_2d__sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'live_2d__setting_section', // id
			'看板娘设置', // title
			array( $this, 'live_2d__section_info' ), // callback
			'live-2d--admin' // page
		);

		add_settings_field(
			'modelapi_0', // id
			'材质API ', // title
			array( $this, 'modelapi_0_callback' ), // callback
			'live-2d--admin', // page
			'live_2d__setting_section' // section
		);

		add_settings_field(
			'tipsmessage_1', // id
			'waifu-tips.json 位置', // title
			array( $this, 'tipsmessage_1_callback' ), // callback
			'live-2d--admin', // page
			'live_2d__setting_section' // section
		);

		add_settings_field(
			'hitokotoapi_2', // id
			'一言 API', // title
			array( $this, 'hitokotoapi_2_callback' ), // callback
			'live-2d--admin', // page
			'live_2d__setting_section' // section
		);

		add_settings_field(
			'modelid_3', // id
			'默认模型 ID', // title
			array( $this, 'modelid_3_callback' ), // callback
			'live-2d--admin', // page
			'live_2d__setting_section' // section
		);

		add_settings_field(
			'modeltexturesid_4', // id
			'默认材质 ID', // title
			array( $this, 'modeltexturesid_4_callback' ), // callback
			'live-2d--admin', // page
			'live_2d__setting_section' // section
		);

		add_settings_field(
			'showtoolmenu_5', // id
			'工具栏', // title
			array( $this, 'showtoolmenu_5_callback' ), // callback
			'live-2d--admin', // page
			'live_2d__setting_section' // section
		);

		add_settings_field(
			'cancloselive2d_6', // id
			'关闭看板娘按钮', // title
			array( $this, 'cancloselive2d_6_callback' ), // callback
			'live-2d--admin', // page
			'live_2d__setting_section' // section
		);

		add_settings_field(
			'canswitchmodel_7', // id
			'模型切换按钮', // title
			array( $this, 'canswitchmodel_7_callback' ), // callback
			'live-2d--admin', // page
			'live_2d__setting_section' // section
		);

		add_settings_field(
			'canswitchtextures_8', // id
			'材质切换按钮', // title
			array( $this, 'canswitchtextures_8_callback' ), // callback
			'live-2d--admin', // page
			'live_2d__setting_section' // section
		);

		add_settings_field(
			'canswitchhitokoto_9', // id
			'一言切换按钮', // title
			array( $this, 'canswitchhitokoto_9_callback' ), // callback
			'live-2d--admin', // page
			'live_2d__setting_section' // section
		);

		add_settings_field(
			'cantakescreenshot_10', // id
			'看板娘截图按钮', // title
			array( $this, 'cantakescreenshot_10_callback' ), // callback
			'live-2d--admin', // page
			'live_2d__setting_section' // section
		);

		add_settings_field(
			'canturntohomepage_11', // id
			'返回首页按钮', // title
			array( $this, 'canturntohomepage_11_callback' ), // callback
			'live-2d--admin', // page
			'live_2d__setting_section' // section
		);

		add_settings_field(
			'canturntoaboutpage_12', // id
			'跳转关于页按钮', // title
			array( $this, 'canturntoaboutpage_12_callback' ), // callback
			'live-2d--admin', // page
			'live_2d__setting_section' // section
		);

		add_settings_field(
			'modelstorage_13', // id
			'记录 ID', // title
			array( $this, 'modelstorage_13_callback' ), // callback
			'live-2d--admin', // page
			'live_2d__setting_section' // section
		);

		
		add_settings_field(
			'modelrandmode_14', // id
			'模型切换方式', // title
			array( $this, 'modelrandmode_14_callback' ), // callback
			'live-2d--admin', // page
			'live_2d__setting_section' // section
		);

		add_settings_field(
			'modeltexturesrandmode_15', // id
			'材质切换方式', // title
			array( $this, 'modeltexturesrandmode_15_callback' ), // callback
			'live-2d--admin', // page
			'live_2d__setting_section' // section
		);

		add_settings_field(
			'showhitokoto_16', // id
			'显示一言', // title
			array( $this, 'showhitokoto_16_callback' ), // callback
			'live-2d--admin', // page
			'live_2d__setting_section' // section
		);

		add_settings_field(
			'showf12status_17', // id
			'显示加载状态', // title
			array( $this, 'showf12status_17_callback' ), // callback
			'live-2d--admin', // page
			'live_2d__setting_section' // section
		);

		add_settings_field(
			'showf12message_18', // id
			'显示看板娘消息', // title
			array( $this, 'showf12message_18_callback' ), // callback
			'live-2d--admin', // page
			'live_2d__setting_section' // section
		);

		add_settings_field(
			'showf12openmsg_19', // id
			'显示控制台打开提示', // title
			array( $this, 'showf12openmsg_19_callback' ), // callback
			'live-2d--admin', // page
			'live_2d__setting_section' // section
		);

		add_settings_field(
			'showcopymessage_20', // id
			'显示 复制内容 提示', // title
			array( $this, 'showcopymessage_20_callback' ), // callback
			'live-2d--admin', // page
			'live_2d__setting_section' // section
		);

		add_settings_field(
			'showwelcomemessage_21', // id
			'显示进入面页欢迎词', // title
			array( $this, 'showwelcomemessage_21_callback' ), // callback
			'live-2d--admin', // page
			'live_2d__setting_section' // section
		);

		add_settings_field(
			'waifusize_22', // id
			'看板娘大小', // title
			array( $this, 'waifusize_22_callback' ), // callback
			'live-2d--admin', // page
			'live_2d__setting_section' // section
		);

		add_settings_field(
			'waifutipssize_23', // id
			'提示框大小', // title
			array( $this, 'waifutipssize_23_callback' ), // callback
			'live-2d--admin', // page
			'live_2d__setting_section' // section
		);

		add_settings_field(
			'waifufontsize_24', // id
			'提示框字体', // title
			array( $this, 'waifufontsize_24_callback' ), // callback
			'live-2d--admin', // page
			'live_2d__setting_section' // section
		);

		add_settings_field(
			'waifutoolfont_25', // id
			'工具栏字体', // title
			array( $this, 'waifutoolfont_25_callback' ), // callback
			'live-2d--admin', // page
			'live_2d__setting_section' // section
		);

		add_settings_field(
			'waifutoolline_26', // id
			'工具栏行高', // title
			array( $this, 'waifutoolline_26_callback' ), // callback
			'live-2d--admin', // page
			'live_2d__setting_section' // section
		);

		add_settings_field(
			'waifutooltop_27', // id
			'工具栏顶部边距', // title
			array( $this, 'waifutooltop_27_callback' ), // callback
			'live-2d--admin', // page
			'live_2d__setting_section' // section
		);

		add_settings_field(
			'waifuminwidth_28', // id
			'面页小于指定宽度 隐藏看板娘 输入disable禁用', // title
			array( $this, 'waifuminwidth_28_callback' ), // callback
			'live-2d--admin', // page
			'live_2d__setting_section' // section
		);

		add_settings_field(
			'waifuedgeside_29', // id
			'看板娘贴边方向', // title
			array( $this, 'waifuedgeside_29_callback' ), // callback
			'live-2d--admin', // page
			'live_2d__setting_section' // section
		);

		add_settings_field(
			'waifudraggable_30', // id
			'拖拽样式', // title
			array( $this, 'waifudraggable_30_callback' ), // callback
			'live-2d--admin', // page
			'live_2d__setting_section' // section
		);

		add_settings_field(
			'waifudraggablerevert_31', // id
			'松开鼠标还原拖拽位置', // title
			array( $this, 'waifudraggablerevert_31_callback' ), // callback
			'live-2d--admin', // page
			'live_2d__setting_section' // section
		);

		add_settings_field(
			'homepageurl_32', // id
			'主页地址', // title
			array( $this, 'homepageurl_32_callback' ), // callback
			'live-2d--admin', // page
			'live_2d__setting_section' // section
		);

		add_settings_field(
			'aboutpageurl_33', // id
			'关于页地址', // title
			array( $this, 'aboutpageurl_33_callback' ), // callback
			'live-2d--admin', // page
			'live_2d__setting_section' // section
		);

		add_settings_field(
			'screenshotcapturename_34', // id
			'看板娘截图文件名', // title
			array( $this, 'screenshotcapturename_34_callback' ), // callback
			'live-2d--admin', // page
			'live_2d__setting_section' // section
		);
	}

	public function live_2d__sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['modelapi_0'] ) ) {
			$sanitary_values['modelapi_0'] = sanitize_text_field( $input['modelapi_0'] );
		}

		if ( isset( $input['tipsmessage_1'] ) ) {
			$sanitary_values['tipsmessage_1'] = sanitize_text_field( $input['tipsmessage_1'] );
		}

		if ( isset( $input['hitokotoapi_2'] ) ) {
			$sanitary_values['hitokotoapi_2'] = $input['hitokotoapi_2'];
		}

		if ( isset( $input['modelid_3'] ) ) {
			$sanitary_values['modelid_3'] = $input['modelid_3'];
		}

		if ( isset( $input['modeltexturesid_4'] ) ) {
			$sanitary_values['modeltexturesid_4'] = sanitize_text_field( $input['modeltexturesid_4'] );
		}

		if ( isset( $input['showtoolmenu_5'] ) ) {
			$sanitary_values['showtoolmenu_5'] = $input['showtoolmenu_5'];
		}

		if ( isset( $input['cancloselive2d_6'] ) ) {
			$sanitary_values['cancloselive2d_6'] = $input['cancloselive2d_6'];
		}

		if ( isset( $input['canswitchmodel_7'] ) ) {
			$sanitary_values['canswitchmodel_7'] = $input['canswitchmodel_7'];
		}

		if ( isset( $input['canswitchtextures_8'] ) ) {
			$sanitary_values['canswitchtextures_8'] = $input['canswitchtextures_8'];
		}

		if ( isset( $input['canswitchhitokoto_9'] ) ) {
			$sanitary_values['canswitchhitokoto_9'] = $input['canswitchhitokoto_9'];
		}

		if ( isset( $input['cantakescreenshot_10'] ) ) {
			$sanitary_values['cantakescreenshot_10'] = $input['cantakescreenshot_10'];
		}

		if ( isset( $input['canturntohomepage_11'] ) ) {
			$sanitary_values['canturntohomepage_11'] = $input['canturntohomepage_11'];
		}

		if ( isset( $input['canturntoaboutpage_12'] ) ) {
			$sanitary_values['canturntoaboutpage_12'] = $input['canturntoaboutpage_12'];
		}

		if ( isset( $input['modelstorage_13'] ) ) {
			$sanitary_values['modelstorage_13'] = $input['modelstorage_13'];
		}

		if ( isset( $input['modelrandmode_14'] ) ) {
			$sanitary_values['modelrandmode_14'] = $input['modelrandmode_14'];
		}

		if ( isset( $input['modeltexturesrandmode_15'] ) ) {
			$sanitary_values['modeltexturesrandmode_15'] = $input['modeltexturesrandmode_15'];
		}

		if ( isset( $input['showhitokoto_16'] ) ) {
			$sanitary_values['showhitokoto_16'] = $input['showhitokoto_16'];
		}

		if ( isset( $input['showf12status_17'] ) ) {
			$sanitary_values['showf12status_17'] = $input['showf12status_17'];
		}

		if ( isset( $input['showf12message_18'] ) ) {
			$sanitary_values['showf12message_18'] = $input['showf12message_18'];
		}

		if ( isset( $input['showf12openmsg_19'] ) ) {
			$sanitary_values['showf12openmsg_19'] = $input['showf12openmsg_19'];
		}

		if ( isset( $input['showcopymessage_20'] ) ) {
			$sanitary_values['showcopymessage_20'] = $input['showcopymessage_20'];
		}

		if ( isset( $input['showwelcomemessage_21'] ) ) {
			$sanitary_values['showwelcomemessage_21'] = $input['showwelcomemessage_21'];
		}

		if ( isset( $input['waifusize_22'] ) ) {
			$sanitary_values['waifusize_22'] = $input['waifusize_22'];
		}

		if ( isset( $input['waifutipssize_23'] ) ) {
			$sanitary_values['waifutipssize_23'] = $input['waifutipssize_23'];
		}

		if ( isset( $input['waifufontsize_24'] ) ) {
			$sanitary_values['waifufontsize_24'] = sanitize_text_field( $input['waifufontsize_24'] );
		}

		if ( isset( $input['waifutoolfont_25'] ) ) {
			$sanitary_values['waifutoolfont_25'] = sanitize_text_field( $input['waifutoolfont_25'] );
		}

		if ( isset( $input['waifutoolline_26'] ) ) {
			$sanitary_values['waifutoolline_26'] = sanitize_text_field( $input['waifutoolline_26'] );
		}

		if ( isset( $input['waifutooltop_27'] ) ) {
			$sanitary_values['waifutooltop_27'] = sanitize_text_field( $input['waifutooltop_27'] );
		}

		if ( isset( $input['waifuminwidth_28'] ) ) {
			$sanitary_values['waifuminwidth_28'] = sanitize_text_field( $input['waifuminwidth_28'] );
		}

		if ( isset( $input['waifuedgeside_29'] ) ) {
			$sanitary_values['waifuedgeside_29'] = sanitize_text_field( $input['waifuedgeside_29'] );
		}

		if ( isset( $input['waifudraggable_30'] ) ) {
			$sanitary_values['waifudraggable_30'] = $input['waifudraggable_30'];
		}

		if ( isset( $input['waifudraggablerevert_31'] ) ) {
			$sanitary_values['waifudraggablerevert_31'] = $input['waifudraggablerevert_31'];
		}

		if ( isset( $input['homepageurl_32'] ) ) {
			$sanitary_values['homepageurl_32'] = sanitize_text_field( $input['homepageurl_32'] );
		}

		if ( isset( $input['aboutpageurl_33'] ) ) {
			$sanitary_values['aboutpageurl_33'] = sanitize_text_field( $input['aboutpageurl_33'] );
		}

		if ( isset( $input['screenshotcapturename_34'] ) ) {
			$sanitary_values['screenshotcapturename_34'] = sanitize_text_field( $input['screenshotcapturename_34'] );
		}

		return $sanitary_values;
	}

	public function live_2d__section_info() {
		
	}

	public function modelapi_0_callback() {
		printf(
			'<input class="regular-text" type="text" name="live_2d__option_name[modelapi_0]" id="modelapi_0" value="%s">',
			isset( $this->live_2d__options['modelapi_0'] ) ? esc_attr( $this->live_2d__options['modelapi_0']) : '//live2d.fghrsh.net/api/'
		);
	}

	public function tipsmessage_1_callback() {
		printf(
			'<input class="regular-text" type="text" name="live_2d__option_name[tipsmessage_1]" id="tipsmessage_1" value="%s">',
			isset( $this->live_2d__options['tipsmessage_1'] ) ? esc_attr( $this->live_2d__options['tipsmessage_1']) : 'waifu-tips.json'
		);
	}

	public function hitokotoapi_2_callback() {
		?> <select name="live_2d__option_name[hitokotoapi_2]" id="hitokotoapi_2">
			<?php $selected = (isset( $this->live_2d__options['hitokotoapi_2'] ) && $this->live_2d__options['hitokotoapi_2'] === 'lwl12.com') ? 'selected' : 'selected' ; ?>
			<option <?php echo $selected; ?>>lwl12.com</option>
			<?php $selected = (isset( $this->live_2d__options['hitokotoapi_2'] ) && $this->live_2d__options['hitokotoapi_2'] === 'hitokoto.cn') ? 'selected' : '' ; ?>
			<option <?php echo $selected; ?>>hitokoto.cn</option>
			<?php $selected = (isset( $this->live_2d__options['hitokotoapi_2'] ) && $this->live_2d__options['hitokotoapi_2'] === 'jinrishici.com') ? 'selected' : '' ; ?>
			<option <?php echo $selected; ?>>jinrishici.com</option>
		</select> <?php
	}

	public function modelid_3_callback() {
		?> <select name="live_2d__option_name[modelid_3]" id="modelid_3">
			<?php $selected = (isset( $this->live_2d__options['modelid_3'] ) && $this->live_2d__options['modelid_3'] === '1') ? 'selected' : 'selected' ; ?>
			<option value="1" <?php echo $selected; ?>>来自药水制作师的 Pio</option>
			<?php $selected = (isset( $this->live_2d__options['modelid_3'] ) && $this->live_2d__options['modelid_3'] === '2') ? 'selected' : '' ; ?>
			<option value="2" <?php echo $selected; ?>>来自药水制作师的 Tia</option>
			<?php $selected = (isset( $this->live_2d__options['modelid_3'] ) && $this->live_2d__options['modelid_3'] === '3') ? 'selected' : '' ; ?>
			<option value="3" <?php echo $selected; ?>>来自 Bilibili Live 的 22</option>
			<?php $selected = (isset( $this->live_2d__options['modelid_3'] ) && $this->live_2d__options['modelid_3'] === '4') ? 'selected' : '' ; ?>
			<option value="4" <?php echo $selected; ?>>来自 Bilibili Live 的 33</option>
			<?php $selected = (isset( $this->live_2d__options['modelid_3'] ) && $this->live_2d__options['modelid_3'] === '5') ? 'selected' : '' ; ?>
			<option value="5" <?php echo $selected; ?>>Shizuku Talk ！这里是 Shizuku</option>
			<?php $selected = (isset( $this->live_2d__options['modelid_3'] ) && $this->live_2d__options['modelid_3'] === '6') ? 'selected' : '' ; ?>
			<option value="6" <?php echo $selected; ?>>超次元游戏：海王星</option>
			<?php $selected = (isset( $this->live_2d__options['modelid_3'] ) && $this->live_2d__options['modelid_3'] === '7') ? 'selected' : '' ; ?>
			<option value="7" <?php echo $selected; ?>>艦隊これくしょん / 叢雲(むらくも)</option>
		</select> <?php
	}

	public function modeltexturesid_4_callback() {
		printf(
			'<input class="regular-text" type="text" name="live_2d__option_name[modeltexturesid_4]" id="modeltexturesid_4" value="%s">',
			isset( $this->live_2d__options['modeltexturesid_4'] ) ? esc_attr( $this->live_2d__options['modeltexturesid_4']) : '53'
		);
	}

	public function showtoolmenu_5_callback() {
		?> <fieldset><?php $checked = ( isset( $this->live_2d__options['showtoolmenu_5'] ) && $this->live_2d__options['showtoolmenu_5'] === 'true' ) ? 'checked' : '' ; ?>
		<label for="showtoolmenu_5-0"><input type="radio" name="live_2d__option_name[showtoolmenu_5]" id="showtoolmenu_5-0" value="true" <?php echo $checked; ?>> 显示</label><br>
		<?php $checked = ( isset( $this->live_2d__options['showtoolmenu_5'] ) && $this->live_2d__options['showtoolmenu_5'] === 'false' ) ? 'checked' : '' ; ?>
		<label for="showtoolmenu_5-1"><input type="radio" name="live_2d__option_name[showtoolmenu_5]" id="showtoolmenu_5-1" value="false" <?php echo $checked; ?>> 隐藏</label></fieldset> <?php
	}

	public function cancloselive2d_6_callback() {
		?> <fieldset><?php $checked = ( isset( $this->live_2d__options['cancloselive2d_6'] ) && $this->live_2d__options['cancloselive2d_6'] === 'true' ) ? 'checked' : '' ; ?>
		<label for="cancloselive2d_6-0"><input type="radio" name="live_2d__option_name[cancloselive2d_6]" id="cancloselive2d_6-0" value="true" <?php echo $checked; ?>> 开启</label><br>
		<?php $checked = ( isset( $this->live_2d__options['cancloselive2d_6'] ) && $this->live_2d__options['cancloselive2d_6'] === 'false' ) ? 'checked' : '' ; ?>
		<label for="cancloselive2d_6-1"><input type="radio" name="live_2d__option_name[cancloselive2d_6]" id="cancloselive2d_6-1" value="false" <?php echo $checked; ?>> 关闭</label></fieldset> <?php
	}

	public function canswitchmodel_7_callback() {
		?> <fieldset><?php $checked = ( isset( $this->live_2d__options['canswitchmodel_7'] ) && $this->live_2d__options['canswitchmodel_7'] === 'true' ) ? 'checked' : '' ; ?>
		<label for="canswitchmodel_7-0"><input type="radio" name="live_2d__option_name[canswitchmodel_7]" id="canswitchmodel_7-0" value="true" <?php echo $checked; ?>> 显示</label><br>
		<?php $checked = ( isset( $this->live_2d__options['canswitchmodel_7'] ) && $this->live_2d__options['canswitchmodel_7'] === 'false' ) ? 'checked' : '' ; ?>
		<label for="canswitchmodel_7-1"><input type="radio" name="live_2d__option_name[canswitchmodel_7]" id="canswitchmodel_7-1" value="false" <?php echo $checked; ?>> 隐藏</label></fieldset> <?php
	}

	public function canswitchtextures_8_callback() {
		?> <fieldset><?php $checked = ( isset( $this->live_2d__options['canswitchtextures_8'] ) && $this->live_2d__options['canswitchtextures_8'] === 'true' ) ? 'checked' : '' ; ?>
		<label for="canswitchtextures_8-0"><input type="radio" name="live_2d__option_name[canswitchtextures_8]" id="canswitchtextures_8-0" value="true" <?php echo $checked; ?>> 显示</label><br>
		<?php $checked = ( isset( $this->live_2d__options['canswitchtextures_8'] ) && $this->live_2d__options['canswitchtextures_8'] === 'false' ) ? 'checked' : '' ; ?>
		<label for="canswitchtextures_8-1"><input type="radio" name="live_2d__option_name[canswitchtextures_8]" id="canswitchtextures_8-1" value="false" <?php echo $checked; ?>> 隐藏</label></fieldset> <?php
	}

	public function canswitchhitokoto_9_callback() {
		?> <fieldset><?php $checked = ( isset( $this->live_2d__options['canswitchhitokoto_9'] ) && $this->live_2d__options['canswitchhitokoto_9'] === 'true' ) ? 'checked' : '' ; ?>
		<label for="canswitchhitokoto_9-0"><input type="radio" name="live_2d__option_name[canswitchhitokoto_9]" id="canswitchhitokoto_9-0" value="true" <?php echo $checked; ?>> 显示</label><br>
		<?php $checked = ( isset( $this->live_2d__options['canswitchhitokoto_9'] ) && $this->live_2d__options['canswitchhitokoto_9'] === 'false' ) ? 'checked' : '' ; ?>
		<label for="canswitchhitokoto_9-1"><input type="radio" name="live_2d__option_name[canswitchhitokoto_9]" id="canswitchhitokoto_9-1" value="false" <?php echo $checked; ?>> 隐藏</label></fieldset> <?php
	}

	public function cantakescreenshot_10_callback() {
		?> <fieldset><?php $checked = ( isset( $this->live_2d__options['cantakescreenshot_10'] ) && $this->live_2d__options['cantakescreenshot_10'] === 'true' ) ? 'checked' : '' ; ?>
		<label for="cantakescreenshot_10-0"><input type="radio" name="live_2d__option_name[cantakescreenshot_10]" id="cantakescreenshot_10-0" value="true" <?php echo $checked; ?>> 显示</label><br>
		<?php $checked = ( isset( $this->live_2d__options['cantakescreenshot_10'] ) && $this->live_2d__options['cantakescreenshot_10'] === 'false' ) ? 'checked' : '' ; ?>
		<label for="cantakescreenshot_10-1"><input type="radio" name="live_2d__option_name[cantakescreenshot_10]" id="cantakescreenshot_10-1" value="false" <?php echo $checked; ?>> 隐藏</label></fieldset> <?php
	}

	public function canturntohomepage_11_callback() {
		?> <fieldset><?php $checked = ( isset( $this->live_2d__options['canturntohomepage_11'] ) && $this->live_2d__options['canturntohomepage_11'] === 'true' ) ? 'checked' : '' ; ?>
		<label for="canturntohomepage_11-0"><input type="radio" name="live_2d__option_name[canturntohomepage_11]" id="canturntohomepage_11-0" value="true" <?php echo $checked; ?>> 显示</label><br>
		<?php $checked = ( isset( $this->live_2d__options['canturntohomepage_11'] ) && $this->live_2d__options['canturntohomepage_11'] === 'false' ) ? 'checked' : '' ; ?>
		<label for="canturntohomepage_11-1"><input type="radio" name="live_2d__option_name[canturntohomepage_11]" id="canturntohomepage_11-1" value="false" <?php echo $checked; ?>> 隐藏</label></fieldset> <?php
	}

	public function canturntoaboutpage_12_callback() {
		?> <fieldset><?php $checked = ( isset( $this->live_2d__options['canturntoaboutpage_12'] ) && $this->live_2d__options['canturntoaboutpage_12'] === 'true' ) ? 'checked' : '' ; ?>
		<label for="canturntoaboutpage_12-0"><input type="radio" name="live_2d__option_name[canturntoaboutpage_12]" id="canturntoaboutpage_12-0" value="true" <?php echo $checked; ?>> 显示</label><br>
		<?php $checked = ( isset( $this->live_2d__options['canturntoaboutpage_12'] ) && $this->live_2d__options['canturntoaboutpage_12'] === 'false' ) ? 'checked' : '' ; ?>
		<label for="canturntoaboutpage_12-1"><input type="radio" name="live_2d__option_name[canturntoaboutpage_12]" id="canturntoaboutpage_12-1" value="false" <?php echo $checked; ?>> 隐藏</label></fieldset> <?php
	}

	public function modelstorage_13_callback() {
		?> <fieldset><?php $checked = ( isset( $this->live_2d__options['modelstorage_13'] ) && $this->live_2d__options['modelstorage_13'] === 'true' ) ? 'checked' : '' ; ?>
		<label for="modelstorage_13-0"><input type="radio" name="live_2d__option_name[modelstorage_13]" id="modelstorage_13-0" value="true" <?php echo $checked; ?>> 显示</label><br>
		<?php $checked = ( isset( $this->live_2d__options['modelstorage_13'] ) && $this->live_2d__options['modelstorage_13'] === 'false' ) ? 'checked' : '' ; ?>
		<label for="modelstorage_13-1"><input type="radio" name="live_2d__option_name[modelstorage_13]" id="modelstorage_13-1" value="false" <?php echo $checked; ?>> 隐藏</label></fieldset> <?php
	}

	public function modelrandmode_14_callback() {
		?> <select name="live_2d__option_name[modelrandmode_14]" id="modelrandmode_14">
			<?php $selected = (isset( $this->live_2d__options['modelrandmode_14'] ) && $this->live_2d__options['modelrandmode_14'] === 'rand') ? 'selected' : '' ; ?>
			<option value="rand" <?php echo $selected; ?>>随机</option>
			<?php $selected = (isset( $this->live_2d__options['modelrandmode_14'] ) && $this->live_2d__options['modelrandmode_14'] === 'switch') ? 'selected' : '' ; ?>
			<option value="switch" <?php echo $selected; ?>>顺序</option>
		</select> <?php
	}

	public function modeltexturesrandmode_15_callback() {
		?> <select name="live_2d__option_name[modeltexturesrandmode_15]" id="modeltexturesrandmode_15">
			<?php $selected = (isset( $this->live_2d__options['modeltexturesrandmode_15'] ) && $this->live_2d__options['modeltexturesrandmode_15'] === 'rand') ? 'selected' : '' ; ?>
			<option value="rand" <?php echo $selected; ?>>随机</option>
			<?php $selected = (isset( $this->live_2d__options['modeltexturesrandmode_15'] ) && $this->live_2d__options['modeltexturesrandmode_15'] === 'switch') ? 'selected' : '' ; ?>
			<option value="switch" <?php echo $selected; ?>>顺序</option>
		</select> <?php
	}

	public function showhitokoto_16_callback() {
		?> <fieldset><?php $checked = ( isset( $this->live_2d__options['showhitokoto_16'] ) && $this->live_2d__options['showhitokoto_16'] === 'true' ) ? 'checked' : '' ; ?>
		<label for="showhitokoto_16-0"><input type="radio" name="live_2d__option_name[showhitokoto_16]" id="showhitokoto_16-0" value="true" <?php echo $checked; ?>> 显示</label><br>
		<?php $checked = ( isset( $this->live_2d__options['showhitokoto_16'] ) && $this->live_2d__options['showhitokoto_16'] === 'false' ) ? 'checked' : '' ; ?>
		<label for="showhitokoto_16-1"><input type="radio" name="live_2d__option_name[showhitokoto_16]" id="showhitokoto_16-1" value="false" <?php echo $checked; ?>> 隐藏</label></fieldset> <?php
	}

	public function showf12status_17_callback() {
		?> <fieldset><?php $checked = ( isset( $this->live_2d__options['showf12status_17'] ) && $this->live_2d__options['showf12status_17'] === 'true' ) ? 'checked' : '' ; ?>
		<label for="showf12status_17-0"><input type="radio" name="live_2d__option_name[showf12status_17]" id="showf12status_17-0" value="true" <?php echo $checked; ?>> 显示</label><br>
		<?php $checked = ( isset( $this->live_2d__options['showf12status_17'] ) && $this->live_2d__options['showf12status_17'] === 'false' ) ? 'checked' : '' ; ?>
		<label for="showf12status_17-1"><input type="radio" name="live_2d__option_name[showf12status_17]" id="showf12status_17-1" value="false" <?php echo $checked; ?>> 隐藏</label></fieldset> <?php
	}

	public function showf12message_18_callback() {
		?> <fieldset><?php $checked = ( isset( $this->live_2d__options['showf12message_18'] ) && $this->live_2d__options['showf12message_18'] === 'true' ) ? 'checked' : '' ; ?>
		<label for="showf12message_18-0"><input type="radio" name="live_2d__option_name[showf12message_18]" id="showf12message_18-0" value="true" <?php echo $checked; ?>> 显示</label><br>
		<?php $checked = ( isset( $this->live_2d__options['showf12message_18'] ) && $this->live_2d__options['showf12message_18'] === 'false' ) ? 'checked' : '' ; ?>
		<label for="showf12message_18-1"><input type="radio" name="live_2d__option_name[showf12message_18]" id="showf12message_18-1" value="false" <?php echo $checked; ?>> 隐藏</label></fieldset> <?php
	}

	public function showf12openmsg_19_callback() {
		?> <fieldset><?php $checked = ( isset( $this->live_2d__options['showf12openmsg_19'] ) && $this->live_2d__options['showf12openmsg_19'] === 'true' ) ? 'checked' : '' ; ?>
		<label for="showf12openmsg_19-0"><input type="radio" name="live_2d__option_name[showf12openmsg_19]" id="showf12openmsg_19-0" value="true" <?php echo $checked; ?>> 显示</label><br>
		<?php $checked = ( isset( $this->live_2d__options['showf12openmsg_19'] ) && $this->live_2d__options['showf12openmsg_19'] === 'false' ) ? 'checked' : '' ; ?>
		<label for="showf12openmsg_19-1"><input type="radio" name="live_2d__option_name[showf12openmsg_19]" id="showf12openmsg_19-1" value="false" <?php echo $checked; ?>> 隐藏</label></fieldset> <?php
	}

	public function showcopymessage_20_callback() {
		?> <fieldset><?php $checked = ( isset( $this->live_2d__options['showcopymessage_20'] ) && $this->live_2d__options['showcopymessage_20'] === 'true' ) ? 'checked' : '' ; ?>
		<label for="showcopymessage_20-0"><input type="radio" name="live_2d__option_name[showcopymessage_20]" id="showcopymessage_20-0" value="true" <?php echo $checked; ?>> 显示</label><br>
		<?php $checked = ( isset( $this->live_2d__options['showcopymessage_20'] ) && $this->live_2d__options['showcopymessage_20'] === 'false' ) ? 'checked' : '' ; ?>
		<label for="showcopymessage_20-1"><input type="radio" name="live_2d__option_name[showcopymessage_20]" id="showcopymessage_20-1" value="false" <?php echo $checked; ?>> 隐藏</label></fieldset> <?php
	}

	public function showwelcomemessage_21_callback() {
		?> <fieldset><?php $checked = ( isset( $this->live_2d__options['showwelcomemessage_21'] ) && $this->live_2d__options['showwelcomemessage_21'] === 'true' ) ? 'checked' : '' ; ?>
		<label for="showwelcomemessage_21-0"><input type="radio" name="live_2d__option_name[showwelcomemessage_21]" id="showwelcomemessage_21-0" value="true" <?php echo $checked; ?>> 显示</label><br>
		<?php $checked = ( isset( $this->live_2d__options['showwelcomemessage_21'] ) && $this->live_2d__options['showwelcomemessage_21'] === 'false' ) ? 'checked' : '' ; ?>
		<label for="showwelcomemessage_21-1"><input type="radio" name="live_2d__option_name[showwelcomemessage_21]" id="showwelcomemessage_21-1" value="false" <?php echo $checked; ?>> 隐藏</label></fieldset> <?php
	}

	public function waifusize_22_callback() {
		?> <select name="live_2d__option_name[waifusize_22]" id="waifusize_22">
			<?php $selected = (isset( $this->live_2d__options['waifusize_22'] ) && $this->live_2d__options['waifusize_22'] === '280x250') ? 'selected' : '' ; ?>
			<option <?php echo $selected; ?>>280x250</option>
			<?php $selected = (isset( $this->live_2d__options['waifusize_22'] ) && $this->live_2d__options['waifusize_22'] === '600x535') ? 'selected' : '' ; ?>
			<option <?php echo $selected; ?>>600x535</option>
		</select> <?php
	}

	public function waifutipssize_23_callback() {
		?> <select name="live_2d__option_name[waifutipssize_23]" id="waifutipssize_23">
			<?php $selected = (isset( $this->live_2d__options['waifutipssize_23'] ) && $this->live_2d__options['waifutipssize_23'] === '250x70') ? 'selected' : '' ; ?>
			<option <?php echo $selected; ?>>250x70</option>
			<?php $selected = (isset( $this->live_2d__options['waifutipssize_23'] ) && $this->live_2d__options['waifutipssize_23'] === '570x150') ? 'selected' : '' ; ?>
			<option <?php echo $selected; ?>>570x150</option>
		</select> <?php
	}

	public function waifufontsize_24_callback() {
		printf(
			'<input class="regular-text" type="text" name="live_2d__option_name[waifufontsize_24]" id="waifufontsize_24" value="%s">',
			isset( $this->live_2d__options['waifufontsize_24'] ) ? esc_attr( $this->live_2d__options['waifufontsize_24']) : '12px'
		);
	}

	public function waifutoolfont_25_callback() {
		printf(
			'<input class="regular-text" type="text" name="live_2d__option_name[waifutoolfont_25]" id="waifutoolfont_25" value="%s">',
			isset( $this->live_2d__options['waifutoolfont_25'] ) ? esc_attr( $this->live_2d__options['waifutoolfont_25']) : '14px'
		);
	}

	public function waifutoolline_26_callback() {
		printf(
			'<input class="regular-text" type="text" name="live_2d__option_name[waifutoolline_26]" id="waifutoolline_26" value="%s">',
			isset( $this->live_2d__options['waifutoolline_26'] ) ? esc_attr( $this->live_2d__options['waifutoolline_26']) : '20px'
		);
	}

	public function waifutooltop_27_callback() {
		printf(
			'<input class="regular-text" type="text" name="live_2d__option_name[waifutooltop_27]" id="waifutooltop_27" value="%s">',
			isset( $this->live_2d__options['waifutooltop_27'] ) ? esc_attr( $this->live_2d__options['waifutooltop_27']) : '0px'
		);
	}

	public function waifuminwidth_28_callback() {
		printf(
			'<input class="regular-text" type="text" name="live_2d__option_name[waifuminwidth_28]" id="waifuminwidth_28" value="%s">',
			isset( $this->live_2d__options['waifuminwidth_28'] ) ? esc_attr( $this->live_2d__options['waifuminwidth_28']) : '768px'
		);
	}

	public function waifuedgeside_29_callback() {
		printf(
			'<input class="regular-text" type="text" name="live_2d__option_name[waifuedgeside_29]" id="waifuedgeside_29" value="%s">',
			isset( $this->live_2d__options['waifuedgeside_29'] ) ? esc_attr( $this->live_2d__options['waifuedgeside_29']) : 'left:0'
		);
	}

	public function waifudraggable_30_callback() {
		?> <select name="live_2d__option_name[waifudraggable_30]" id="waifudraggable_30">
			<?php $selected = (isset( $this->live_2d__options['waifudraggable_30'] ) && $this->live_2d__options['waifudraggable_30'] === 'disable') ? 'selected' : '' ; ?>
			<option value="disable" <?php echo $selected; ?>>禁用</option>
			<?php $selected = (isset( $this->live_2d__options['waifudraggable_30'] ) && $this->live_2d__options['waifudraggable_30'] === 'axis-x') ? 'selected' : '' ; ?>
			<option value="axis-x" <?php echo $selected; ?>>只能水平拖拽</option>
			<?php $selected = (isset( $this->live_2d__options['waifudraggable_30'] ) && $this->live_2d__options['waifudraggable_30'] === 'unlimited') ? 'selected' : '' ; ?>
			<option value="unlimited" <?php echo $selected; ?>>自由拖拽</option>
		</select> <?php
	}

	public function waifudraggablerevert_31_callback() {
		?> <fieldset><?php $checked = ( isset( $this->live_2d__options['waifudraggablerevert_31'] ) && $this->live_2d__options['waifudraggablerevert_31'] === 'true' ) ? 'checked' : '' ; ?>
		<label for="waifudraggablerevert_31-0"><input type="radio" name="live_2d__option_name[waifudraggablerevert_31]" id="waifudraggablerevert_31-0" value="true" <?php echo $checked; ?>> 还原</label><br>
		<?php $checked = ( isset( $this->live_2d__options['waifudraggablerevert_31'] ) && $this->live_2d__options['waifudraggablerevert_31'] === 'false' ) ? 'checked' : '' ; ?>
		<label for="waifudraggablerevert_31-1"><input type="radio" name="live_2d__option_name[waifudraggablerevert_31]" id="waifudraggablerevert_31-1" value="false" <?php echo $checked; ?>> 不还原</label></fieldset> <?php
	}

	public function homepageurl_32_callback() {
		printf(
			'<input class="regular-text" type="text" name="live_2d__option_name[homepageurl_32]" id="homepageurl_32" value="%s">',
			isset( $this->live_2d__options['homepageurl_32'] ) ? esc_attr( $this->live_2d__options['homepageurl_32']) : 'auto'
		);
	}

	public function aboutpageurl_33_callback() {
		printf(
			'<input class="regular-text" type="text" name="live_2d__option_name[aboutpageurl_33]" id="aboutpageurl_33" value="%s">',
			isset( $this->live_2d__options['aboutpageurl_33'] ) ? esc_attr( $this->live_2d__options['aboutpageurl_33']) : '#'
		);
	}

	public function screenshotcapturename_34_callback() {
		printf(
			'<input class="regular-text" type="text" name="live_2d__option_name[screenshotcapturename_34]" id="screenshotcapturename_34" value="%s">',
			isset( $this->live_2d__options['screenshotcapturename_34'] ) ? esc_attr( $this->live_2d__options['screenshotcapturename_34']) : 'live2d.png'
		);
	}

}
if ( is_admin() )
	$live_2d_ = new LiveD();


//进行设置
function live2D_DefMod(){
// Retrieve this value with:
$live_2d__options = get_option( 'live_2d__option_name' ); // Array of All Options
?>
	<div class="waifu">
        <div class="waifu-tips"></div>
        <canvas id="live2d" class="live2d"></canvas>
        <div class="waifu-tool">
            <span class="fui-home"></span>
            <span class="fui-chat"></span>
            <span class="fui-eye"></span>
            <span class="fui-user"></span>
            <span class="fui-photo"></span>
            <span class="fui-info-circle"></span>
            <span class="fui-cross"></span>
        </div>
    </div>
	<script type="text/javascript">
		<?php
			// 后端接口
			if (isset($live_2d__options['modelapi_0'])){?>
				live2d_settings["modelAPI"] = "<?php echo $live_2d__options['modelapi_0'] ?>";
		<?php
			}
			if (isset($live_2d__options['tipsmessage_1'])){?>
				live2d_settings["tipsMessage"] = "<?php echo $live_2d__options['tipsmessage_1'] ?>";
		<?php
			}
			if (isset($live_2d__options['hitokotoapi_2'])){?>
				live2d_settings["hitokotoAPI"] = "<?php echo $live_2d__options['hitokotoapi_2'] ?>";
		<?php
			}
			// 默认模型
			if (isset($live_2d__options['modelid_3'])){?>
				live2d_settings["modelId"] = "<?php echo $live_2d__options['modelid_3'] ?>";
		<?php
			}
			if (isset($live_2d__options['modeltexturesid_4'])){?>
				live2d_settings["modelTexturesId"] = "<?php echo $live_2d__options['modeltexturesid_4'] ?>";
		<?php
			}
			// 工具栏设置
			if (isset($live_2d__options['showtoolmenu_5'])){?>
				live2d_settings["showToolMenu"] = "<?php echo $live_2d__options['showtoolmenu_5'] ?>";
		<?php
			}
			if (isset($live_2d__options['cancloselive2d_6'])){?>
				live2d_settings["canCloseLive2d"] = "<?php echo $live_2d__options['cancloselive2d_6'] ?>";
		<?php
			}
			if (isset($live_2d__options['canswitchmodel_7'])){?>
				live2d_settings["canSwitchModel"] = "<?php echo $live_2d__options['canswitchmodel_7'] ?>";
		<?php
			}
			if (isset($live_2d__options['canswitchtextures_8'])){?>
				live2d_settings["canSwitchTextures"] = "<?php echo $live_2d__options['canswitchtextures_8'] ?>";
		<?php
			}
			if (isset($live_2d__options['canswitchhitokoto_9'])){?>
				live2d_settings["canSwitchHitokoto"] = "<?php echo $live_2d__options['canswitchhitokoto_9'] ?>";
		<?php
			}
			if (isset($live_2d__options['cantakescreenshot_10'])){?>
				live2d_settings["canTakeScreenshot"] = "<?php echo $live_2d__options['cantakescreenshot_10'] ?>";
		<?php
			}
			if (isset($live_2d__options['canturntohomepage_11'])){?>
				live2d_settings["canTurnToHomePage"] = "<?php echo $live_2d__options['canturntohomepage_11'] ?>";
		<?php
			}
			if (isset($live_2d__options['canturntoaboutpage_12'])){?>
				live2d_settings["canTurnToAboutPage"] = "<?php echo $live_2d__options['canturntoaboutpage_12'] ?>";
		<?php
			}
			// 模型切换模式
			if (isset($live_2d__options['modelstorage_13'])){?>
				live2d_settings["modelStorage"] = "<?php echo $live_2d__options['modelstorage_13'] ?>";
		<?php
			}
			if (isset($live_2d__options['modelrandmode_14'])){?>
				live2d_settings["modelRandMode"] = "<?php echo $live_2d__options['modelrandmode_14'] ?>";
		<?php
			}
			if (isset($live_2d__options['modeltexturesrandmode_15'])){?>
				live2d_settings["modelTexturesRandMode"] = "<?php echo $live_2d__options['modeltexturesrandmode_15'] ?>";
		<?php
			}
			// 提示消息选项
			if (isset($live_2d__options['showhitokoto_16'])){?>
				live2d_settings["showHitokoto"] = "<?php echo $live_2d__options['showhitokoto_16'] ?>";
		<?php
			}
			if (isset($live_2d__options['showf12status_17'])){?>
				live2d_settings["showF12Status"] = "<?php echo $live_2d__options['showf12status_17'] ?>";
		<?php
			}
			if (isset($live_2d__options['showf12message_18'])){?>
				live2d_settings["showF12Message"] = "<?php echo $live_2d__options['showf12message_18'] ?>";
		<?php
			}
			if (isset($live_2d__options['showf12openmsg_19'])){?>
				live2d_settings["showF12OpenMsg"] = "<?php echo $live_2d__options['showf12openmsg_19'] ?>";
		<?php
			}
			if (isset($live_2d__options['showcopymessage_20'])){?>
				live2d_settings["showCopyMessage"] = "<?php echo $live_2d__options['showcopymessage_20'] ?>";
		<?php
			}
			if (isset($live_2d__options['showwelcomemessage_21'])){?>
				live2d_settings["showWelcomeMessage"] = "<?php echo $live_2d__options['showwelcomemessage_21'] ?>";
		<?php
			}
			//看板娘样式设置
			if (isset($live_2d__options['waifusize_22'])){?>
				live2d_settings["waifuSize"] = "<?php echo $live_2d__options['waifusize_22'] ?>";
		<?php
			}
			if (isset($live_2d__options['waifutipssize_23'])){?>
				live2d_settings["waifuTipsSize"] = "<?php echo $live_2d__options['waifutipssize_23'] ?>";
		<?php
			}
			if (isset($live_2d__options['waifufontsize_24'])){?>
				live2d_settings["waifuFontSize"] = "<?php echo $live_2d__options['waifufontsize_24'] ?>";
		<?php
			}
			if (isset($live_2d__options['waifutoolfont_25'])){?>
				live2d_settings["waifuToolFont"] = "<?php echo $live_2d__options['waifutoolfont_25'] ?>";
		<?php
			}
			if (isset($live_2d__options['waifutoolline_26'])){?>
				live2d_settings["waifuToolLine"] = "<?php echo $live_2d__options['waifutoolline_26'] ?>";
		<?php
			}
			if (isset($live_2d__options['waifutooltop_27'])){?>
				live2d_settings["waifuToolTop"] = "<?php echo $live_2d__options['waifutooltop_27'] ?>";
		<?php
			}
			if (isset($live_2d__options['waifuminwidth_28'])){?>
				live2d_settings["waifuMinWidth"] = "<?php echo $live_2d__options['waifuminwidth_28'] ?>";
		<?php
			}
			if (isset($live_2d__options['waifuedgeside_29'])){?>
				live2d_settings["waifuEdgeSide"] = "<?php echo $live_2d__options['waifuedgeside_29'] ?>";
		<?php
			}
			if (isset($live_2d__options['waifudraggable_30'])){?>
				live2d_settings["waifuDraggable"] = "<?php echo $live_2d__options['waifudraggable_30'] ?>";
		<?php
			}
			if (isset($live_2d__options['waifudraggablerevert_31'])){?>
				live2d_settings["waifuDraggableRevert"] = "<?php echo $live_2d__options['waifudraggablerevert_31'] ?>";
		<?php
			}
			// 其他杂项设置
			if (isset($live_2d__options['homepageurl_32'])){?>
				live2d_settings["homePageUrl"] = "<?php echo $live_2d__options['homepageurl_32'] ?>";
		<?php
			}
			if (isset($live_2d__options['aboutpageurl_33'])){?>
				live2d_settings["aboutPageUrl"] = "<?php echo $live_2d__options['aboutpageurl_33'] ?>";
		<?php
			}
			if (isset($live_2d__options['screenshotcapturename_34'])){?>
				live2d_settings["screenshotCaptureName"] = "<?php echo $live_2d__options['screenshotcapturename_34'] ?>";
		<?php
			}
		?>
        initModel("<?php echo LIVE2D_ASSETS ?>waifu-tips.json");
    </script>
<?php
}
add_action( 'wp_footer', 'live2D_DefMod' );
?>
